# AI-CloudOps 测试配置文件
# 可以通过环境变量覆盖这些默认值

# 基础配置
export TEST_ROUNDS=${TEST_ROUNDS:-3}
export PERFORMANCE_TESTS=${PERFORMANCE_TESTS:-10}
export MAX_RESPONSE_TIME=${MAX_RESPONSE_TIME:-5}
export CONCURRENT_LIMIT=${CONCURRENT_LIMIT:-5}

# API配置
export TEST_API_HOST=${TEST_API_HOST:-"localhost"}
export TEST_API_PORT=${TEST_API_PORT:-8000}
export API_TIMEOUT=${API_TIMEOUT:-30}

# 测试数据配置
export ENABLE_PERFORMANCE_TEST=${ENABLE_PERFORMANCE_TEST:-true}
export ENABLE_STRESS_TEST=${ENABLE_STRESS_TEST:-false}
export ENABLE_BOUNDARY_TEST=${ENABLE_BOUNDARY_TEST:-true}

# 日志配置
export LOG_LEVEL=${LOG_LEVEL:-"INFO"}
export SAVE_DETAILED_LOGS=${SAVE_DETAILED_LOGS:-true}
export CLEANUP_OLD_LOGS=${CLEANUP_OLD_LOGS:-true}

# 报告配置
export GENERATE_HTML_REPORT=${GENERATE_HTML_REPORT:-false}
export SEND_EMAIL_REPORT=${SEND_EMAIL_REPORT:-false}
export EMAIL_RECIPIENTS=${EMAIL_RECIPIENTS:-""}

echo "测试配置已加载"